import requests
import base64
import os

# Дані для авторизації
USERNAME = "odata"
PASSWORD = "zX8a7M36yU"
APIKEY = "917881f0-62a2-4f37-a826-bf08ef581239"

# Дані по документу
DOCUMENT_ID = "50e104c8-482f-11f0-8124-ee42ca3fce4f"  # замінити на актуальне
DOCUMENT_TYPE = "diagnostic"

# URL
BASE_URL = "https://app.enote.vet/7edc4405-f8d6-4022-9999-8186ee1ce262-copy"
ENDPOINT = f"{BASE_URL}/hs/api/v2/AttachedFiles"
PARAMS = {
    "documentId": DOCUMENT_ID,
    "documentType": DOCUMENT_TYPE
}
HEADERS = {
    "apikey": APIKEY
}

# Запит
response = requests.get(ENDPOINT, headers=HEADERS, params=PARAMS, auth=(USERNAME, PASSWORD))

if response.status_code == 200:
    files = response.json()
    os.makedirs("downloaded_from_enote", exist_ok=True)

    for file in files:
        ext = file.get("fileExtension", ".bin").replace(".", "")
        file_data = file.get("fileData")
        name = file.get("description", "file")

        if file_data:
            binary = base64.b64decode(file_data)
            path = os.path.join("downloaded_from_enote", f"{name}.{ext}")
            with open(path, "wb") as f:
                f.write(binary)
            print(f"[+] Файл збережено: {path}")
        else:
            print("[!] У файлі немає fileData")
else:
    print(f"[!] Помилка {response.status_code}")
    print(response.text)
